name: Main CI

on: push

jobs:
  Init_and_test:
    name: Init and Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.12.1
        cache: npm
    - name: Initialise npm
      run: npm ci
    - name: Perform Static Analysis with ESLint
      run: npx eslint -o eslint_report.json -f json || true
      continue-on-error: true
    - name: Create ESLint Annotations
      uses: ataylorme/eslint-annotate-action@v3
      with:
        only-pr-files: false
    - name: Run Jest Tests
      run: npm test
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Set up Docker Build Tools
      uses: docker/setup-buildx-action@v3
    - name: Build test image and push to docker hub
      uses: docker/build-push-action@v5  
      with:
        context: .
        file: Dockerfiles/test.Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/iatd_repos:test-latest

    - name: Build user image and push to docker hub
      uses: docker/build-push-action@v5  
      with:
        context: .
        file: Dockerfiles/user.Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/iatd_repos:user-latest